import Head from 'next/head';
import { Inter } from 'next/font/google'; // Ensure you have this dependency installed
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Gan Wei Cai | Portfolio',
  name: 'Wei Cai',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name={metadata.name} content={metadata.description} />
        {/* Link to your favicon */}
        <link rel="icon" href="/app/favicon.ico" />
        {/* Include any other metadata or stylesheets here */}
      </Head>
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
